/// feather ignore all
/// @ignore
function __gmlspeak_constant_preset_io_keyboard(ffi) {
	ffi.exposeDynamicConstant( 
		"keyboard_key", function() {return keyboard_key;},
		"keyboard_lastkey", function() {return keyboard_lastkey;},
		"keyboard_lastchar", function() {return keyboard_lastchar;},
		
	);
	
	ffi.exposeConstant(
		"vk_nokey",			vk_nokey,
		"vk_anykey",		vk_anykey,
		"vk_enter",			vk_enter,
		"vk_return",		vk_return,
		"vk_shift",			vk_shift,
		"vk_control",		vk_control,
		"vk_alt",			vk_alt,
		"vk_escape",		vk_escape,
		"vk_space",			vk_space,
		"vk_backspace",		vk_backspace,
		"vk_tab",			vk_tab,
		"vk_pause",			vk_pause,
		"vk_printscreen",	vk_printscreen,
		"vk_left",			vk_left,
		"vk_right",			vk_right,
		"vk_up",			vk_up,
		"vk_down",			vk_down,
		"vk_home",			vk_home,
		"vk_end",			vk_end,
		"vk_delete",		vk_delete,
		"vk_insert",		vk_insert,
		"vk_pageup",		vk_pageup,
		"vk_pagedown",		vk_pagedown,
		"vk_f1",			vk_f1,
		"vk_f2",			vk_f2,
		"vk_f3",			vk_f3,
		"vk_f4",			vk_f4,
		"vk_f5",			vk_f5,
		"vk_f6",			vk_f6,
		"vk_f7",			vk_f7,
		"vk_f8",			vk_f8,
		"vk_f9",			vk_f9,
		"vk_f10",			vk_f10,
		"vk_f11",			vk_f11,
		"vk_f12",			vk_f12, 
		"vk_numpad0",		vk_numpad0,
		"vk_numpad1",		vk_numpad1,
		"vk_numpad2",		vk_numpad2,
		"vk_numpad3",		vk_numpad3,
		"vk_numpad4",		vk_numpad4,
		"vk_numpad5",		vk_numpad5,
		"vk_numpad6",		vk_numpad6,
		"vk_numpad7",		vk_numpad7,
		"vk_numpad8",		vk_numpad8,
		"vk_numpad9",		vk_numpad9,
		"vk_divide",		vk_divide,
		"vk_multiply",		vk_multiply,
		"vk_subtract",		vk_subtract,
		"vk_add",			vk_add,
		"vk_decimal",		vk_decimal,
		"vk_lshift",		vk_lshift,
		"vk_lcontrol",		vk_lcontrol,
		"vk_lalt",			vk_lalt,
		"vk_rshift",		vk_rshift,
		"vk_rcontrol",		vk_rcontrol,
		"vk_ralt",			vk_ralt
	);
	
	ffi.exposeConstant( 
		"kbv_type_default",						kbv_type_default,
		"kbv_type_ascii",						kbv_type_ascii,
		"kbv_type_url",							kbv_type_url,
		"kbv_type_email",						kbv_type_email,
		"kbv_type_numbers",						kbv_type_numbers,
		"kbv_type_phone",						kbv_type_phone,
		"kbv_type_phone_name",					kbv_type_phone_name,
		"kbv_returnkey_default",				kbv_returnkey_default,
		"kbv_returnkey_go",						kbv_returnkey_go,
		"kbv_returnkey_google",					kbv_returnkey_google,
		"kbv_returnkey_join",					kbv_returnkey_join,
		"kbv_returnkey_next",					kbv_returnkey_next,
		"kbv_returnkey_route",					kbv_returnkey_route,
		"kbv_returnkey_search",					kbv_returnkey_search,
		"kbv_returnkey_send",					kbv_returnkey_send,
		"kbv_returnkey_yahoo",					kbv_returnkey_yahoo,
		"kbv_returnkey_done",					kbv_returnkey_done,
		"kbv_returnkey_continue",				kbv_returnkey_continue,
		"kbv_returnkey_emergency",				kbv_returnkey_emergency,
		"kbv_autocapitalize_none",				kbv_autocapitalize_none,
		"kbv_autocapitalize_words",				kbv_autocapitalize_words,
		"kbv_autocapitalize_sentences",			kbv_autocapitalize_sentences,
		"kbv_autocapitalize_characters",		kbv_autocapitalize_characters
	);
}