/// feather ignore all
/// @ignore
function __gmlspeak_constant_preset_events(ffi) {
	ffi.exposeDynamicConstant( 
		"event_type", function() {return event_type;},
		"event_number", function() {return event_number;},
		"async_load", function() {return async_load;},
		"event_data", function() {return event_data;},
	);
	
	ffi.exposeConstant( 
		"ev_create", ev_create,
		"ev_no_more_lives", ev_no_more_lives,
		"ev_no_more_health", ev_no_more_health,
		
		"ev_gesture", ev_gesture,
		"ev_gesture_double_tap", ev_gesture_double_tap,
		"ev_gesture_drag_end", ev_gesture_drag_end,
		"ev_gesture_drag_start", ev_gesture_drag_start,
		"ev_gesture_dragging", ev_gesture_dragging,
		"ev_gesture_tap", ev_gesture_tap,
		"ev_gesture_rotating", ev_gesture_rotating,
		"ev_gesture_rotate_end", ev_gesture_rotate_end,
		"ev_gesture_rotate_start", ev_gesture_rotate_start,
		"ev_gesture_flick", ev_gesture_flick,
		"ev_gesture_pinch_start", ev_gesture_pinch_start,
		"ev_gesture_pinch_in", ev_gesture_pinch_in,
		"ev_gesture_pinch_out", ev_gesture_pinch_out,
		"ev_gesture_pinch_end", ev_gesture_pinch_end,
		
		// This seems to not exist, but it also does?? idk, crashes
		//"ev_global_gesture", ev_global_gesture,
		"ev_global_gesture_double_tap", ev_global_gesture_double_tap,
		"ev_global_gesture_drag_end", ev_global_gesture_drag_end,
		"ev_global_gesture_drag_start", ev_global_gesture_drag_start,
		"ev_global_gesture_dragging", ev_global_gesture_dragging,
		"ev_global_gesture_tap", ev_global_gesture_tap,
		"ev_global_gesture_rotating", ev_global_gesture_rotating,
		"ev_global_gesture_rotate_end", ev_global_gesture_rotate_end,
		"ev_global_gesture_rotate_start", ev_global_gesture_rotate_start,
		"ev_global_gesture_flick", ev_global_gesture_flick,
		"ev_global_gesture_pinch_start", ev_global_gesture_pinch_start,
		"ev_global_gesture_pinch_in", ev_global_gesture_pinch_in,
		"ev_global_gesture_pinch_out", ev_global_gesture_pinch_out,
		"ev_global_gesture_pinch_end", ev_global_gesture_pinch_end,
		
		"ev_destroy", ev_destroy,
		"ev_step", ev_step,
		"ev_alarm", ev_alarm,
		"ev_keyboard", ev_keyboard,
		"ev_mouse", ev_mouse,
		"ev_collision", ev_collision,
		"ev_other", ev_other,
		"ev_draw", ev_draw,
		"ev_keypress", ev_keypress,
		"ev_keyrelease", ev_keyrelease,
		"ev_cleanup", ev_cleanup,
		"ev_gesture", ev_gesture,
		"ev_room_end", ev_room_end,
		"ev_room_start", ev_room_start,
		"ev_game_end", ev_game_end,
		"ev_game_start", ev_game_start,
		"ev_pre_create", ev_pre_create,
		"ev_left_button", ev_left_button,
		"ev_right_button", ev_right_button,
		"ev_middle_button", ev_middle_button,
		"ev_no_button", ev_no_button,
		"ev_left_press", ev_left_press,
		"ev_right_press", ev_right_press,
		"ev_middle_press", ev_middle_press,
		"ev_left_release", ev_left_release,
		"ev_right_release", ev_right_release,
		"ev_middle_release", ev_middle_release,
		"ev_mouse_enter", ev_mouse_enter,
		"ev_mouse_leave", ev_mouse_leave,
		"ev_global_left_press", ev_global_left_press,
		"ev_global_right_press", ev_global_right_press,
		"ev_global_left_release", ev_global_left_release,
		"ev_global_right_release", ev_global_right_release,
		"ev_global_left_button", ev_global_left_button,
		"ev_global_right_button", ev_global_right_button,
		"ev_global_middle_press", ev_global_middle_press,
		"ev_global_middle_release", ev_global_middle_release,
		"ev_global_middle_button", ev_global_middle_button,
		"ev_draw_begin", ev_draw_begin,
		"ev_draw_end", ev_draw_end,
		"ev_draw_pre", ev_draw_pre,
		"ev_draw_post", ev_draw_post,
		"ev_gui_begin", ev_gui_begin,
		"ev_gui_end", ev_gui_end,
		"ev_gui", ev_gui,
		"ev_user0", ev_user0,
		"ev_user1", ev_user1,
		"ev_user2", ev_user2,
		"ev_user3", ev_user3,
		"ev_user4", ev_user4,
		"ev_user5", ev_user5,
		"ev_user6", ev_user6,
		"ev_user7", ev_user7,
		"ev_user8", ev_user8,
		"ev_user9", ev_user9,
		"ev_user10", ev_user10,
		"ev_user11", ev_user11,
		"ev_user12", ev_user12,
		"ev_user13", ev_user13,
		"ev_user14", ev_user14,
		"ev_user15", ev_user15,
		"ev_animation_end", ev_animation_end,
		"ev_end_of_path", ev_end_of_path,
		"ev_outside", ev_outside,
		"ev_boundary", ev_boundary,
		"ev_mouse_wheel_down", ev_mouse_wheel_down,
		"ev_mouse_wheel_up", ev_mouse_wheel_up,
		"ev_outside_view0", ev_outside_view0,
		"ev_outside_view1", ev_outside_view1,
		"ev_outside_view2", ev_outside_view2,
		"ev_outside_view3", ev_outside_view3,
		"ev_outside_view4", ev_outside_view4,
		"ev_outside_view5", ev_outside_view5,
		"ev_outside_view6", ev_outside_view6,
		"ev_outside_view7", ev_outside_view7,
		"ev_boundary_view0", ev_boundary_view0,
		"ev_boundary_view1", ev_boundary_view1,
		"ev_boundary_view2", ev_boundary_view2,
		"ev_boundary_view3", ev_boundary_view3,
		"ev_boundary_view4", ev_boundary_view4,
		"ev_boundary_view5", ev_boundary_view5,
		"ev_boundary_view6", ev_boundary_view6,
		"ev_boundary_view7", ev_boundary_view7,
		"ev_collision", ev_collision,
		"ev_broadcast_message", ev_broadcast_message,
		"ev_step_normal", ev_step_normal,
		"ev_step_begin", ev_step_begin,
		"ev_step_end", ev_step_end
	);
	
	ffi.exposeConstant( 
		"ev_async_system_event", ev_async_system_event,
		"ev_async_push_notification", ev_async_push_notification,
		"ev_async_web_iap", ev_async_web_iap,
		"ev_async_social", ev_async_social,
		"ev_async_web", ev_async_web,
		"ev_async_web_cloud", ev_async_web_cloud,
		"ev_async_web_image_load", ev_async_web_image_load,
		"ev_async_web_networking", ev_async_web_networking,
		"ev_async_web_steam", ev_async_web_steam,
		"ev_async_audio_playback", ev_async_audio_playback,
		"ev_async_audio_recording", ev_async_audio_recording,
		"ev_async_dialog", ev_async_dialog,
		"ev_async_save_load", ev_async_save_load
	);
	
	try {
		ffi.exposeConstant( 
			// Not in LTS
			"ev_draw_normal", ev_draw_normal
		);
	} catch(_) {
		__gmlspeak_log("ev_draw_normal not available! Skipping...");	
		} 
}