/// feather ignore all
/// @ignore
function __gmlspeak_constant_preset_physics(ffi) {
	ffi.exposeConstant( 
		"phy_joint_anchor_1_x",				phy_joint_anchor_1_x,
		"phy_joint_anchor_1_y",				phy_joint_anchor_1_y,
		"phy_joint_anchor_2_x",				phy_joint_anchor_2_x,
		"phy_joint_anchor_2_y",				phy_joint_anchor_2_y,
		"phy_joint_reaction_force_x",		phy_joint_reaction_force_x,
		"phy_joint_reaction_force_y",		phy_joint_reaction_force_y,
		"phy_joint_reaction_torque",		phy_joint_reaction_torque,
		"phy_joint_max_motor_force",		phy_joint_max_motor_force,
		"phy_joint_max_motor_torque",		phy_joint_max_motor_torque,
		"phy_joint_motor_force",			phy_joint_motor_force,
		"phy_joint_motor_speed",			phy_joint_motor_speed,
		"phy_joint_motor_torque",			phy_joint_motor_torque,
		"phy_joint_angle",					phy_joint_angle,
		"phy_joint_angle_limits",			phy_joint_angle_limits,
		"phy_joint_upper_angle_limit",		phy_joint_upper_angle_limit,
		"phy_joint_lower_angle_limit",		phy_joint_lower_angle_limit,
		"phy_joint_translation",			phy_joint_translation,
		"phy_joint_speed",					phy_joint_speed,
		"phy_joint_damping_ratio",			phy_joint_damping_ratio,
		"phy_joint_frequency",				phy_joint_frequency,
		"phy_joint_length_1",				phy_joint_length_1,
		"phy_joint_length_2",				phy_joint_length_2,
		"phy_joint_max_torque",				phy_joint_max_torque,
		"phy_joint_max_force",				phy_joint_max_force,
		"phy_joint_max_length",				phy_joint_max_length,
		"phy_particle_flag_water",			phy_particle_flag_water,
		"phy_particle_flag_zombie",			phy_particle_flag_zombie,
		"phy_particle_flag_wall",			phy_particle_flag_wall,
		"phy_particle_flag_spring",			phy_particle_flag_spring,
		"phy_particle_flag_elastic",		phy_particle_flag_elastic,
		"phy_particle_flag_viscous",		phy_particle_flag_viscous,
		"phy_particle_flag_powder",			phy_particle_flag_powder,
		"phy_particle_flag_tensile",		phy_particle_flag_tensile,
		"phy_particle_flag_colourmixing	",	phy_particle_flag_colourmixing,
		"phy_particle_flag_colormixing",	phy_particle_flag_colormixing,
		"phy_particle_data_flag_typeflags",	phy_particle_data_flag_typeflags,
		"phy_particle_data_flag_position",	phy_particle_data_flag_position,
		"phy_particle_data_flag_velocity",	phy_particle_data_flag_velocity,
		"phy_particle_data_flag_colour",	phy_particle_data_flag_colour,
		"phy_particle_data_flag_color",		phy_particle_data_flag_colour,
		"phy_particle_data_flag_category",	phy_particle_data_flag_category,
		"phy_particle_group_flag_solid",	phy_particle_group_flag_solid,
		"phy_particle_group_flag_rigid",	phy_particle_group_flag_rigid,
		"phy_debug_render_aabb",			phy_debug_render_aabb,
		"phy_debug_render_collision_pairs",	phy_debug_render_collision_pairs,
		"phy_debug_render_coms",			phy_debug_render_coms,
		"phy_debug_render_core_shapes",		phy_debug_render_core_shapes,
		"phy_debug_render_joints",			phy_debug_render_joints,
		"phy_debug_render_obb",				phy_debug_render_obb,
		"phy_debug_render_shapes",			phy_debug_render_shapes
	);
}